languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "tahmidul612"
description = "Hi! I'm Tahmidul"
copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[params]
  # mainSections = ["section1", "section2"]

[author]
  name = "Tahmidul Islam"
  image = "img/profile.jpg"
  headline = "I love computers, coding, scifi books, and isekai anime"
  bio = "I'm a computer science student at Lakehead University. I started coding because it was fun, and it's still fun to learn about new things every day. Automation is my most recent interest, because I am super lazy and if I can get a computer to my job for me, I will (even if it takes longer than just doing it myself)."
  links = [
    { email = "mailto:tahmidul612@gmail.com" },
    { facebook = "https://facebook.com/tahmidul612" },
    { github = "https://github.com/tahmidul612" },
    { instagram = "https://instagram.com/thelittolprince" },
    { linkedin = "https://linkedin.com/in/tahmidul612" }
  ]
